# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "CI"

on:
  - pull_request
  - push

permissions:
  contents: read

jobs:
  ci:
    name: "Run CI"

    uses: "mimmi20/template/.github/workflows/ci.yml@updates"
    with:
      extensions: "json, opcache"
      ini-values: "opcache.enable=1, opcache.fast_shutdown=0, zend.assertions=1, assert.exception=On, intl.default_locale=de, intl.use_exceptions=1, zend.exception_ignore_args=0"
      composer-options: "--optimize-autoloader --prefer-dist --prefer-stable -v"
      min-covered-msi: 77
      min-msi: 61
      composer-outdated-option: ""
    secrets:
      envPAT: "${{ secrets.GITHUB_TOKEN }}"
